name: ssh_key
version: 0.8.0
description: Encodes and decodes keys to/from different text file formats.
homepage: https://github.com/hoylen/ssh_key

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asn1lib: '^1.0.0'
  pointycastle: '^3.2.0'
  tuple: '^2.0.0'

# Important: pointycastle 3.1.3 introduced a bug with large integers,
# making it impossible to compile to JavaScript. Therefore, this
# must use 3.2.0 or newer.

dev_dependencies:
  coverage: ^1.5.0
  lints: ^1.0.1
  test: '^1.15.4'
