name: ssh_key
version: 1.0.0
description: Encodes and decodes keys to/from different text file formats.
homepage: https://github.com/hoylen/ssh_key

environment:
  sdk: '^3.0.0'

dependencies:
  asn1lib: '^1.0.0'
  pointycastle: '^3.7.3'

dev_dependencies:
  coverage: ^1.5.0
  lints: ^2.1.1
  pana: ^0.21.37
  test: '^1.15.4'

false_secrets:
  - test/rsa_2048bits_test.dart
  - test/textual_encoding_test.dart
