name: ssh_key
version: 0.7.0
description: Encodes and decodes keys to/from different text file formats.
homepage: https://github.com/hoylen/ssh_key

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asn1lib: '^1.0.0'
  pointycastle: '^3.0.1'
  tuple: '^2.0.0'

dev_dependencies:
  test: '^1.15.4'
