name: ssh_key
version: 0.6.0
description: Encodes and decodes keys to/from different text file formats.
homepage: https://github.com/hoylen/ssh_key

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  asn1lib: '^0.8.1'
  pointycastle: '^2.0.0'
  tuple: '^1.0.3'

dev_dependencies:
  test: '^1.15.4'
